---
abstract: 'ANSI to IRC and HTML converter'
author:
  - 'Mischa S. <revmischa@cpan.org>'
build_requires:
  Test::More: 0.88
configure_requires:
  Module::Build::Tiny: 0.019
dynamic_config: 0
generated_by: 'Dist::Milla version v1.0.1, Dist::Zilla version 4.300034, CPAN::Meta::Converter version 2.130880'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: ansi-unicode
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
requires:
  Getopt::Long: 0
  perl: 5.008005
resources:
  bugtracker: https://github.com/revmischa/ansi-unicode/issues
  homepage: https://github.com/revmischa/ansi-unicode
  repository: https://github.com/revmischa/ansi-unicode.git
version: 0.02
x_contributors:
  - 'Mischa S <revmischa@cpan.org>'
